Repository AztecProtocol/AZTEC, pull requests merged in 2019-08, with the labels that each got.

#210 Emit noteRegistry creation event in NoteRegistry.sol
  packages/protocol/contracts/ACE/NoteRegistry.sol
  packages/protocol/test/ACE/NoteRegistry.js
Labels: enhancement

#235 Update contract-artifacts export
  packages/contract-artifacts/src/index.js
  yarn.lock
Labels: bug

#238 Update README.md
  README.md
Labels: enhancement

#239 build(monorepo-scripts): update contract deployment names
  packages/monorepo-scripts/addresses/update.js
  packages/monorepo-scripts/artifacts/build.js
Labels: bug

#193 Feat public range proof
  packages/aztec.js/src/proof/index.js
  packages/aztec.js/src/proof/publicRange/helpers.js
  packages/aztec.js/src/proof/publicRange/index.js
  packages/aztec.js/src/proof/publicRange/verifier.js
  packages/aztec.js/src/proof/types.js
  packages/aztec.js/test/proof/privateRange/verifier.js
  packages/aztec.js/test/proof/publicRange/index.js
  packages/aztec.js/test/proof/publicRange/verifier.js
  packages/contract-artifacts/src/index.js
  packages/dev-utils/src/proofs.js
  packages/monorepo-scripts/addresses/update.js
  packages/monorepo-scripts/artifacts/build.js
  packages/protocol/contracts/ACE/validators/publicRange/PublicRange.sol
  packages/protocol/contracts/ACE/validators/publicRange/PublicRangeABIEncoder.sol
  packages/protocol/contracts/interfaces/IAZTEC.sol
  packages/protocol/contracts/interfaces/PublicRangeInterface.sol
  packages/protocol/contracts/test/ACE/validators/publicRange/PublicRangeABIEncoderTest.sol
  packages/protocol/test/ACE/validators/dividend/abiEncoder.js
  packages/protocol/test/ACE/validators/publicRange/abiEncoder.js
  packages/protocol/test/ACE/validators/publicRange/index.js
  packages/protocol/test/helpers/proof.js
Labels: feature

#209 Refactor EIP712 to be consistent with MetaMask
  packages/aztec.js/package.json
  packages/aztec.js/src/proof/joinSplit/index.js
  packages/aztec.js/src/signer/index.js
  packages/aztec.js/test/signer/index.js
  packages/protocol/contracts/libs/LibEIP712.sol
  packages/protocol/test/ERC1724/ZkAsset.js
  packages/protocol/test/ERC1724/ZkAssetAdjustable.js
  packages/protocol/test/ERC1724/ZkAssetMintable.js
  packages/protocol/test/ERC1724/ZkAssetOwnable.js
  packages/protocol/test/libs/LibEIP712.js
  yarn.lock
Labels: enhancement

#243 build: add factory contracts into artifact gen and build deployment
  packages/contract-artifacts/src/index.js
  packages/monorepo-scripts/addresses/update.js
Labels: bug

#245 Feat add upgrade to ownable
  packages/protocol/contracts/ACE/noteRegistry/NoteRegistryManager.sol
  packages/protocol/contracts/ACE/noteRegistry/interfaces/NoteRegistryFactory.sol
  packages/protocol/contracts/ACE/noteRegistry/interfaces/ProxyAdmin.sol
  packages/protocol/contracts/ERC1724/base/ZkAssetOwnableBase.sol
  packages/protocol/contracts/test/ACE/TestFactory.sol
  packages/protocol/test/ACE/NoteRegistry.js
  packages/protocol/test/ACE/NoteRegistry/NoteRegistryManager.js
  packages/protocol/test/ACE/NoteRegistry/epochs/201907/NoteRegistry.js
  packages/protocol/test/ERC1724/ZkAssetOwnable.js
Labels: bug, feature

#249 Fix burn note event log
  packages/protocol/contracts/ERC1724/base/ZkAssetBurnableBase.sol
Labels: bug

#248 Update JSDocs
  packages/aztec.js/src/proof/joinSplit/index.js
  packages/aztec.js/src/proof/joinSplitFluid/burn/index.js
  packages/aztec.js/src/proof/joinSplitFluid/index.js
  packages/aztec.js/src/proof/joinSplitFluid/mint/index.js
Labels: enhancement

#246 Add docs links in the readMe
  README.md
  packages/aztec.js/README.md
Labels: enhancement

#254 Migrate ace join split fluid tests
  packages/protocol/test/ACE/ACE.js
  packages/protocol/test/ACE/ACEJoinSplitFluid.js
  packages/protocol/test/ACE/NoteRegistry/NoteRegistryManager.js
  packages/protocol/test/ACE/NoteRegistry/epochs/201907/NoteRegistry.js
  packages/protocol/test/ERC1724/ZkAssetBurnable.js
  packages/protocol/test/ERC1724/ZkAssetOwnable.js
  packages/protocol/test/helpers/Factory.js
  packages/protocol/test/helpers/note.js
Labels: enhancement

#260 Add PublicRange.sol deployment script
  packages/protocol/migrations/10_deploy_adjustableFactory.js
  packages/protocol/migrations/11_deploy_mixedFactory.js
  packages/protocol/migrations/12_deploy_zk_asset.js
  packages/protocol/migrations/8_deploy_public_range.js
  packages/protocol/migrations/9_deploy_baseFactory.js
Labels: bug

#244 Refactor meta data for granting view key access
  packages/aztec.js/src/encoder/inputCoder.js
  packages/aztec.js/src/encoder/outputCoder.js
  packages/aztec.js/src/index.js
  packages/aztec.js/src/metaData/index.js
  packages/aztec.js/src/note/index.js
  packages/aztec.js/src/note/utils.js
  packages/aztec.js/src/proof/dividend/index.js
  packages/aztec.js/src/proof/joinSplit/index.js
  packages/aztec.js/src/proof/joinSplitFluid/burn/index.js
  packages/aztec.js/src/proof/joinSplitFluid/index.js
  packages/aztec.js/src/proof/joinSplitFluid/mint/index.js
  packages/aztec.js/src/proof/privateRange/index.js
  packages/aztec.js/src/proof/proof.js
  packages/aztec.js/src/proof/publicRange/index.js
  packages/aztec.js/src/proof/swap/index.js
  packages/aztec.js/test/encoder/inputCoder.js
  packages/aztec.js/test/encoder/outputCoder.js
  packages/aztec.js/test/metaData/index.js
  packages/aztec.js/test/note/index.js
  packages/aztec.js/test/proof/joinSplit/index.js
  packages/dev-utils/src/constants.js
  packages/protocol/contracts/ACE/validators/joinSplitFluid/JoinSplitFluidABIEncoder.sol
  packages/protocol/contracts/ACE/validators/swap/SwapABIEncoder.sol
  packages/protocol/contracts/ERC1724/base/ZkAssetBase.sol
  packages/protocol/contracts/ERC1724/base/ZkAssetMintableBase.sol
  packages/protocol/contracts/interfaces/IZkAsset.sol
  packages/protocol/contracts/libs/MetaDataUtils.sol
  packages/protocol/contracts/test/ERC1724/ZkAssetTest.sol
  packages/protocol/test/ACE/ACE.js
  packages/protocol/test/ACE/validators/joinSplit/abiEncoder.js
  packages/protocol/test/ACE/validators/swap/abiEncoder.js
  packages/protocol/test/ACE/validators/swap/index.js
  packages/protocol/test/ERC1724/ZkAsset.js
  packages/protocol/test/ERC1724/ZkAssetMintable.js
Labels: bug, enhancement, feature, help wanted

#256 [Help wanted] Tests for notes over a fake trusted setup public key
  packages/protocol/contracts/ACE/validators/swap/Swap.sol
  packages/protocol/test/ACE/validators/dividend/index.js
  packages/protocol/test/ACE/validators/joinSplit/index.js
  packages/protocol/test/ACE/validators/joinSplitFluid/index.js
  packages/protocol/test/ACE/validators/privateRange/index.js
  packages/protocol/test/ACE/validators/publicRange/index.js
  packages/protocol/test/ACE/validators/swap/index.js
  packages/protocol/test/helpers/proof.js
Labels: enhancement, help wanted

#303 docs(protocol): update docs for contracts
  packages/protocol/contracts/ACE/ACEOwner.sol
  packages/protocol/contracts/ACE/validators/dividend/Dividend.sol
  packages/protocol/contracts/ACE/validators/dividend/DividendABIEncoder.sol
  packages/protocol/contracts/ACE/validators/joinSplit/JoinSplit.sol
  packages/protocol/contracts/ACE/validators/joinSplit/JoinSplitABIEncoder.sol
  packages/protocol/contracts/ACE/validators/joinSplitFluid/JoinSplitFluid.sol
  packages/protocol/contracts/ACE/validators/joinSplitFluid/JoinSplitFluidABIEncoder.sol
  packages/protocol/contracts/ACE/validators/privateRange/PrivateRange.sol
  packages/protocol/contracts/ACE/validators/privateRange/PrivateRangeABIEncoder.sol
  packages/protocol/contracts/ACE/validators/publicRange/PublicRange.sol
  packages/protocol/contracts/ACE/validators/publicRange/PublicRangeABIEncoder.sol
  packages/protocol/contracts/ACE/validators/swap/Swap.sol
  packages/protocol/contracts/ACE/validators/swap/SwapABIEncoder.sol
  packages/protocol/contracts/ERC1724/base/ZkAssetBase.sol
  packages/protocol/contracts/ERC1724/base/ZkAssetOwnableBase.sol
  packages/protocol/contracts/interfaces/DividendInterface.sol
  packages/protocol/contracts/interfaces/IAZTEC.sol
  packages/protocol/contracts/interfaces/IZkAsset.sol
  packages/protocol/contracts/interfaces/IZkAssetBurnable.sol
  packages/protocol/contracts/interfaces/JoinSplitFluidInterface.sol
  packages/protocol/contracts/interfaces/PrivateRangeInterface.sol
  packages/protocol/contracts/interfaces/PublicRangeInterface.sol
  packages/protocol/contracts/interfaces/SwapInterface.sol
  packages/protocol/contracts/libs/MetaDataUtils.sol
  packages/protocol/contracts/libs/NoteUtils.sol
  packages/protocol/contracts/libs/ProofUtils.sol
  packages/protocol/contracts/libs/SafeMath8.sol
  packages/protocol/contracts/libs/VersioningUtils.sol
  packages/protocol/contracts/test/ACE/ACETest.sol
  packages/protocol/contracts/test/ACE/BehaviourWithConflictTest.sol
  packages/protocol/contracts/test/ACE/validators/dividend/DividendABIEncoderTest.sol
  packages/protocol/contracts/test/ACE/validators/joinSplit/JoinSplitABIEncoderTest.sol
  packages/protocol/contracts/test/ACE/validators/joinSplitFluid/JoinSplitFluidABIEncoderTest.sol
  packages/protocol/contracts/test/ACE/validators/privateRange/PrivateRangeABIEncoderTest.sol
  packages/protocol/contracts/test/ACE/validators/publicRange/PublicRangeABIEncoderTest.sol
  packages/protocol/contracts/test/libs/LibEIP712Test.sol
  packages/protocol/contracts/test/libs/NoteUtilsTest.sol
  packages/protocol/contracts/test/libs/ProofUtilsTest.sol
  packages/protocol/contracts/test/libs/SafeMath8Test.sol
Labels: enhancement
