Repository AztecProtocol/AZTEC, pull requests merged in 2019-04, with the labels that each got.

#81 [WIP] Enhancement documentation
  packages/aztec.js/package-lock.json
  packages/aztec.js/src/abiEncoder/encoderFactory.js
  packages/aztec.js/src/abiEncoder/inputCoder.js
  packages/aztec.js/src/abiEncoder/noteCoder.js
  packages/aztec.js/src/abiEncoder/outputCoder.js
  packages/aztec.js/src/bn128/index.js
  packages/aztec.js/src/note/index.js
  packages/aztec.js/src/note/utils.js
  packages/aztec.js/src/proof/bilateralSwap/index.js
  packages/aztec.js/src/proof/bilateralSwap/verifier.js
  packages/aztec.js/src/proof/dividendComputation/index.js
  packages/aztec.js/src/proof/dividendComputation/verifier.js
  packages/aztec.js/src/proof/joinSplit/extractor.js
  packages/aztec.js/src/proof/joinSplit/helpers.js
  packages/aztec.js/src/proof/joinSplit/index.js
  packages/aztec.js/src/proof/joinSplit/verifier.js
  packages/aztec.js/src/proof/proofUtils.js
  packages/aztec.js/src/secp256k1/index.js
  packages/aztec.js/src/sign/eip712.js
  packages/aztec.js/src/sign/index.js
  packages/aztec.js/src/typeDefs.js
  packages/contract-addresses/.jsdoc.json
  packages/contract-addresses/package-lock.json
  packages/contract-addresses/package.json
  packages/contract-artifacts/package-lock.json
  packages/contract-artifacts/package.json
  packages/dev-utils/.jsdoc.json
  packages/dev-utils/package-lock.json
  packages/dev-utils/package.json
  packages/dev-utils/src/errors.js
  packages/dev-utils/src/exceptions.js
  packages/protocol/.jsdoc.json
  packages/protocol/contracts/ACE/ACE.sol
  packages/protocol/contracts/ACE/NoteRegistry.sol
  packages/protocol/contracts/ACE/validators/bilateralSwap/BilateralSwap.sol
  packages/protocol/contracts/ACE/validators/bilateralSwap/BilateralSwapABIEncoder.sol
  packages/protocol/contracts/ACE/validators/bilateralSwap/BilateralSwapABIEncoderTest.sol
  packages/protocol/contracts/ACE/validators/dividendComputation/DividendComputation.sol
  packages/protocol/contracts/ACE/validators/dividendComputation/DividendComputationABIEncoder.sol
  packages/protocol/contracts/ACE/validators/dividendComputation/DividendComputationABIEncoderTest.sol
  packages/protocol/contracts/ACE/validators/joinSplit/JoinSplit.sol
  packages/protocol/contracts/ACE/validators/joinSplit/JoinSplitABIEncoder.sol
  packages/protocol/contracts/ZkAsset/IZkAsset.sol
  packages/protocol/contracts/ZkAsset/ZkAsset.sol
  packages/protocol/contracts/ZkAsset/ZkAssetDetailed.sol
  packages/protocol/contracts/ZkAsset/ZkAssetOwnable.sol
  packages/protocol/contracts/ZkAsset/ZkAssetOwnableTest.sol
  packages/protocol/contracts/libs/IntegerUtils.sol
  packages/protocol/contracts/libs/NoteUtils.sol
  packages/protocol/contracts/libs/ProofUtils.sol
  packages/protocol/contracts/libs/SafeMath8.sol
  packages/protocol/package-lock.json
  packages/protocol/package.json
Labels: enhancement

#90 Docs zk asset
  packages/protocol/contracts/ERC1724/ZkAssetBurnable.sol
  packages/protocol/contracts/ERC1724/ZkAssetMintable.sol
Labels: enhancement

#98 feat(contract-artifacts): make repo isomorphic
  packages/contract-artifacts/package.json
  packages/contract-artifacts/src/index.js
Labels: enhancement, feature

#116 Build and publish docs in CI
  .circleci/config.yml
  package.json
  packages/aztec.js/package.json
Labels: enhancement

#117 Change points database url to CloudFront distribution
  packages/aztec.js/src/setup/index.js
Labels: bug
