Repository AztecProtocol/AZTEC, pull requests merged in 2019-02, with the labels that each got.

#36 Prune unused dependencies and fix babel-runtime bug
  .circleci/config.yml
  packages/aztec.js/package-lock.json
  packages/aztec.js/package.json
  packages/contract-addresses/package-lock.json
  packages/contract-addresses/package.json
  packages/contract-artifacts/package-lock.json
  packages/contract-artifacts/package.json
  packages/dev-utils/package-lock.json
  packages/dev-utils/package.json
  packages/dev-utils/src/constants.js
  packages/protocol/test/ZKERC20/ZKERC20.js
Labels: enhancement

#24 WIP - Feat bilateral swap
  packages/aztec.js/package-lock.json
  packages/aztec.js/package.json
  packages/aztec.js/src/note/index.js
  packages/aztec.js/src/proof/bilateralSwap/helpers.js
  packages/aztec.js/src/proof/bilateralSwap/index.js
  packages/aztec.js/src/proof/bilateralSwap/verifier.js
  packages/aztec.js/src/proof/index.js
  packages/aztec.js/test/proof/bilateralSwap/proof.spec.js
  packages/aztec.js/test/proof/bilateralSwap/verifier.spec.js
  packages/aztec.js/test/proof/joinSplit/extractor.spec.js
  packages/aztec.js/test/proof/joinSplit/proof.spec.js
  packages/aztec.js/test/proof/joinSplit/verifier.spec.js
  packages/protocol/contracts/ACE/NoteRegistry.sol
  packages/protocol/contracts/AZTEC/BilateralSwap.sol
  packages/protocol/package-lock.json
  packages/protocol/package.json
  packages/protocol/test/AZTEC/bilateralSwap.js
Labels: feature

#23 WIP- Feat dividend computation
  packages/aztec.js/package-lock.json
  packages/aztec.js/package.json
  packages/aztec.js/src/proof/dividendComputation/helpers.js
  packages/aztec.js/src/proof/dividendComputation/index.js
  packages/aztec.js/src/proof/dividendComputation/verifier.js
  packages/aztec.js/src/proof/index.js
  packages/aztec.js/test/proof/dividendComputation/proof.spec.js
  packages/aztec.js/test/proof/dividendComputation/verifier.spec.js
  packages/protocol/contracts/AZTEC/DividendCalc.sol
  packages/protocol/package-lock.json
  packages/protocol/package.json
  packages/protocol/test/AZTEC/dividendCalc.js
Labels: feature

#40 Zero knowledge bilateral swap and dividend computation merge
  packages/aztec.js/package-lock.json
  packages/aztec.js/package.json
  packages/aztec.js/src/note/index.js
  packages/aztec.js/src/proof/bilateralSwap/helpers.js
  packages/aztec.js/src/proof/bilateralSwap/index.js
  packages/aztec.js/src/proof/bilateralSwap/verifier.js
  packages/aztec.js/src/proof/dividendComputation/helpers.js
  packages/aztec.js/src/proof/dividendComputation/index.js
  packages/aztec.js/src/proof/dividendComputation/verifier.js
  packages/aztec.js/src/proof/index.js
  packages/aztec.js/test/proof/bilateralSwap/proof.spec.js
  packages/aztec.js/test/proof/bilateralSwap/verifier.spec.js
  packages/aztec.js/test/proof/dividendComputation/proof.spec.js
  packages/aztec.js/test/proof/dividendComputation/verifier.spec.js
  packages/aztec.js/test/proof/joinSplit/extractor.spec.js
  packages/aztec.js/test/proof/joinSplit/proof.spec.js
  packages/aztec.js/test/proof/joinSplit/verifier.spec.js
  packages/protocol/contracts/ACE/NoteRegistry.sol
  packages/protocol/contracts/AZTEC/BilateralSwap.sol
  packages/protocol/contracts/AZTEC/DividendCalc.sol
  packages/protocol/package-lock.json
  packages/protocol/package.json
  packages/protocol/test/AZTEC/bilateralSwap.js
  packages/protocol/test/AZTEC/dividendCalc.js
  packages/protocol/test/ZKERC20/zkERC20.js
Labels: feature

#43 Get rid of unnecessary comments
  packages/aztec.js/src/proof/bilateralSwap/index.js
  packages/aztec.js/src/proof/dividendComputation/index.js
  packages/aztec.js/src/proof/joinSplit/index.js
  packages/aztec.js/test/abiEncoder/joinSplit.spec.js
  packages/aztec.js/test/abiEncoder/outputCoder.spec.js
Labels: enhancement

#41 Feat aggregate constants
  packages/aztec.js/package-lock.json
  packages/aztec.js/package.json
  packages/aztec.js/src/params.js
  packages/aztec.js/src/proof/joinSplit/index.js
  packages/contract-addresses/package-lock.json
  packages/contract-artifacts/package-lock.json
  packages/dev-utils/package-lock.json
  packages/dev-utils/package.json
  packages/dev-utils/src/constants.js
  packages/huff/package-lock.json
  packages/protocol/contracts/ACE/validators/JoinSplit/JoinSplit.sol
  packages/protocol/contracts/ACE/validators/JoinSplit/JoinSplitABIEncoder.sol
  packages/protocol/demo/src/contracts/aztec/controller.js
  packages/protocol/demo/src/contracts/aztecToken/controller.spec.js
  packages/protocol/migrations/3_deploy_joinsplit.js
  packages/protocol/migrations/6_deploy_old_aztec.js
  packages/protocol/package-lock.json
  packages/protocol/package.json
  packages/protocol/test/ACE/ACE.js
  packages/protocol/test/ACE/NoteRegistry.js
  packages/protocol/test/ACE/validators/JoinSplit.js
  packages/protocol/test/ACE/validators/JoinSplitABIEncoder.js
  packages/protocol/test/AZTEC/aztec.js
  packages/protocol/test/AZTEC/aztecERC20Bridge.js
  packages/protocol/test/ZKERC20/ZKERC20.js
  packages/weierstrudel/node_modules/bn.js/package.json
  packages/weierstrudel/package-lock.json
Labels: enhancement

#44 Set CRS and proof on ACE after deployment
  packages/protocol/migrations/2_deploy_ace.js
  packages/protocol/migrations/3_deploy_joinsplit.js
Labels: bug

#45 Reorder contracts in a new utils directory
  PULL_REQUEST_TEMPLATE.md
  packages/protocol/contracts/ACE/ACE.sol
  packages/protocol/contracts/ACE/NoteRegistry.sol
  packages/protocol/contracts/utils/Doorbell.sol
  packages/protocol/contracts/utils/NoteUtilities.sol
Labels: enhancement

#48 Bug confidential token migrations
  packages/protocol/migrations/4_deploy_token.js
Labels: bug

#49 Fix chain id bug
  packages/aztec.js/README.md
  packages/aztec.js/package.json
  packages/aztec.js/src/params.js
  packages/aztec.js/src/proof/joinSplit/index.js
  packages/aztec.js/src/sign/index.js
  packages/aztec.js/test/abiEncoder/joinSplit.spec.js
  packages/aztec.js/test/sign/eip712.spec.js
  packages/aztec.js/test/sign/sign.spec.js
  packages/contract-addresses/package-lock.json
  packages/contract-addresses/package.json
  packages/contract-addresses/src/index.js
  packages/contract-artifacts/artifacts/ACE.json
  packages/contract-artifacts/artifacts/AZTEC.json
  packages/contract-artifacts/artifacts/AZTECERC20Bridge.json
  packages/contract-artifacts/artifacts/AZTECInterface.json
  packages/contract-artifacts/artifacts/BilateralSwap.json
  packages/contract-artifacts/artifacts/BilateralSwapInterface.json
  packages/contract-artifacts/artifacts/DividendCalc.json
  packages/contract-artifacts/artifacts/DividendCalcInterface.json
  packages/contract-artifacts/artifacts/Doorbell.json
  packages/contract-artifacts/artifacts/EIP712Utils.json
  packages/contract-artifacts/artifacts/ERC20.json
  packages/contract-artifacts/artifacts/ERC20Interface.json
  packages/contract-artifacts/artifacts/ERC20Mintable.json
  packages/contract-artifacts/artifacts/IERC20.json
  packages/contract-artifacts/artifacts/JoinSplit.json
  packages/contract-artifacts/artifacts/JoinSplitABIEncoder.json
  packages/contract-artifacts/artifacts/JoinSplitInterface.json
  packages/contract-artifacts/artifacts/NoteRegistry.json
  packages/contract-artifacts/artifacts/NoteUtilities.json
  packages/contract-artifacts/artifacts/ZKERC20.json
  packages/contract-artifacts/artifacts/ZkERC20.json
  packages/contract-artifacts/package-lock.json
  packages/contract-artifacts/package.json
  packages/dev-utils/package-lock.json
  packages/dev-utils/package.json
  packages/dev-utils/src/constants.js
  packages/protocol/contracts/ACE/validators/JoinSplit/JoinSplit.sol
  packages/protocol/contracts/ACE/validators/JoinSplit/JoinSplitABIEncoder.sol
  packages/protocol/contracts/AZTEC/AZTECERC20Bridge.sol
  packages/protocol/contracts/ZKERC20/ZKERC20.sol
  packages/protocol/demo/src/notes/controller.js
  packages/protocol/migrations/3_deploy_joinsplit.js
  packages/protocol/migrations/6_deploy_old_aztec.js
  packages/protocol/package-lock.json
  packages/protocol/package.json
  packages/protocol/test/ACE/ACE.js
  packages/protocol/test/ACE/NoteRegistry.js
  packages/protocol/test/ACE/validators/JoinSplit.js
  packages/protocol/test/ACE/validators/JoinSplitABIEncoder.js
  packages/protocol/test/AZTEC/aztecERC20Bridge.js
  packages/protocol/test/ZKERC20/ZKERC20.js
Labels: bug

#52 Various enhancements
  packages/aztec.js/package.json
  packages/aztec.js/src/proof/joinSplit/index.js
  packages/protocol/contracts/ACE/ACE.sol
  packages/protocol/contracts/ACE/NoteRegistry.sol
  packages/protocol/migrations/4_deploy_token.js
  packages/protocol/package-lock.json
  packages/protocol/package.json
  packages/protocol/test/ACE/ACE.js
  packages/protocol/test/ACE/NoteRegistry.js
  packages/protocol/test/ACE/validators/JoinSplit.js
  packages/protocol/test/ZKERC20/ZKERC20.js
Labels: enhancement

#57 Fix lowercase issue with ZKERC20
  packages/protocol/test/ZKERC20/zkERC20.js
  packages/protocol/test/zkERC20/zkERC20.js
Labels: bug

#46 Feat LibEIP712
  packages/aztec.js/package-lock.json
  packages/aztec.js/package.json
  packages/aztec.js/src/bn128/index.js
  packages/aztec.js/src/index.js
  packages/aztec.js/src/params.js
  packages/aztec.js/src/proof/dividendComputation/verifier.js
  packages/aztec.js/src/proof/joinSplit/index.js
  packages/aztec.js/src/setup/index.js
  packages/aztec.js/src/sign/index.js
  packages/aztec.js/test/abiEncoder/encoderFactory.spec.js
  packages/aztec.js/test/abiEncoder/outputCoder.spec.js
  packages/aztec.js/test/bn128/bn128.spec.js
  packages/aztec.js/test/note/note.spec.js
  packages/aztec.js/test/proof/bilateralSwap/proof.spec.js
  packages/aztec.js/test/proof/bilateralSwap/verifier.spec.js
  packages/aztec.js/test/proof/dividendComputation/verifier.spec.js
  packages/aztec.js/test/proof/joinSplit/extractor.spec.js
  packages/aztec.js/test/proof/joinSplit/proof.spec.js
  packages/aztec.js/test/proof/joinSplit/verifier.spec.js
  packages/aztec.js/test/setup/setup.spec.js
  packages/aztec.js/test/sign/sign.spec.js
  packages/dev-utils/package-lock.json
  packages/dev-utils/package.json
  packages/dev-utils/src/constants.js
  packages/protocol/contracts/ACE/validators/JoinSplit/JoinSplit.sol
  packages/protocol/contracts/ACE/validators/JoinSplit/JoinSplitABIEncoder.sol
  packages/protocol/contracts/ACE/validators/bilateralSwap/BilateralSwapABIEncoder.sol
  packages/protocol/contracts/ACE/validators/dividendComputation/DividendComputationABIEncoder.sol
  packages/protocol/contracts/ZKERC20/ZKERC20.sol
  packages/protocol/contracts/libs/LibEIP712.sol
  packages/protocol/package-lock.json
  packages/protocol/package.json
  packages/protocol/test/ACE/ACE.js
  packages/protocol/test/ACE/NoteRegistry.js
  packages/protocol/test/ACE/validators/bilateralSwap/abiEncoder.js
  packages/protocol/test/ACE/validators/bilateralSwap/index.js
  packages/protocol/test/ACE/validators/dividendComputation/ABIEncoder.js
  packages/protocol/test/ACE/validators/dividendComputation/abiEncoder.js
  packages/protocol/test/ACE/validators/dividendComputation/index.js
  packages/protocol/test/ACE/validators/joinSplit/abiEncoder.js
  packages/protocol/test/ACE/validators/joinSplit/index.js
  packages/protocol/test/ZKERC20/ZKERC20.js
Labels: enhancement, feature

#58 Feat decode events
  packages/aztec.js/package-lock.json
  packages/aztec.js/package.json
  packages/aztec.js/src/abiEncoder/index.js
  packages/aztec.js/src/abiEncoder/noteCoder.js
  packages/aztec.js/src/bn128/decodePoint.js
  packages/aztec.js/src/bn128/index.js
  packages/aztec.js/src/bn128/mcl/.babelrc
  packages/aztec.js/src/bn128/mcl/mcl.js
  packages/aztec.js/src/bn128/mcl/mcl_c.js
  packages/aztec.js/src/bn128/mcl/mcl_c.wasm
  packages/aztec.js/src/bn128/mcl/mcl_c512.js
  packages/aztec.js/src/bn128/mcl/mcl_c512.wasm
  packages/aztec.js/src/note/index.js
  packages/aztec.js/test/bn128/bn128.spec.js
  packages/aztec.js/test/note/note.spec.js
Labels: feature
