Repository AztecProtocol/AZTEC, pull requests merged in 2019-03, with the labels that each got.

#55 Minor fixes to AZTEC demo README
  packages/aztec.js/README.md
Labels: enhancement

#59 Update version of aztec.js
  packages/aztec.js/package-lock.json
  packages/aztec.js/package.json
Labels: enhancement

#63 Add babel-runtime fix in aztec.js
  packages/aztec.js/.babelrc
  packages/aztec.js/package-lock.json
  packages/aztec.js/package.json
Labels: bug

#54 Feat SafeMath
  packages/protocol/contracts/ACE/NoteRegistry.sol
  packages/protocol/contracts/ZKERC20/ZKERC20.sol
  packages/protocol/contracts/utils/IntegerUtils.sol
  packages/protocol/package-lock.json
  packages/protocol/package.json
Labels: enhancement

#56 Feat error improve + proof API improvement
  packages/aztec.js/package-lock.json
  packages/aztec.js/package.json
  packages/aztec.js/src/proof/bilateralSwap/helpers.js
  packages/aztec.js/src/proof/bilateralSwap/index.js
  packages/aztec.js/src/proof/bilateralSwap/verifier.js
  packages/aztec.js/src/proof/dividendComputation/helpers.js
  packages/aztec.js/src/proof/dividendComputation/index.js
  packages/aztec.js/src/proof/dividendComputation/verifier.js
  packages/aztec.js/src/proof/index.js
  packages/aztec.js/src/proof/joinSplit/extractor.js
  packages/aztec.js/src/proof/joinSplit/index.js
  packages/aztec.js/src/proof/joinSplit/verifier.js
  packages/aztec.js/src/proof/proofUtils.js
  packages/aztec.js/test/abiEncoder/encoderFactory.spec.js
  packages/aztec.js/test/proof/bilateralSwap/proof.spec.js
  packages/aztec.js/test/proof/bilateralSwap/verifier.spec.js
  packages/aztec.js/test/proof/dividendComputation/proof.spec.js
  packages/aztec.js/test/proof/dividendComputation/verifier.spec.js
  packages/aztec.js/test/proof/joinSplit/extractor.spec.js
  packages/aztec.js/test/proof/joinSplit/proof.spec.js
  packages/aztec.js/test/proof/joinSplit/verifier.spec.js
  packages/dev-utils/package.json
  packages/dev-utils/src/constants.js
  packages/dev-utils/src/errors.js
  packages/dev-utils/src/index.js
  packages/protocol/package-lock.json
  packages/protocol/package.json
  packages/protocol/test/ACE/NoteRegistry.js
  packages/protocol/test/ACE/validators/bilateralSwap/abiEncoder.js
  packages/protocol/test/ACE/validators/bilateralSwap/index.js
  packages/protocol/test/ACE/validators/joinSplit/abiEncoder.js
Labels: enhancement, feature

#67 Fix path import
  packages/aztec.js/package-lock.json
  packages/aztec.js/package.json
  packages/aztec.js/src/index.js
  packages/dev-utils/package-lock.json
  packages/dev-utils/package.json
  packages/dev-utils/src/index.js
  packages/protocol/package-lock.json
Labels: bug

#68 New proof versioning + various other things
  .solhint.json
  package-lock.json
  packages/aztec.js/package-lock.json
  packages/aztec.js/package.json
  packages/aztec.js/src/note/index.js
  packages/aztec.js/src/proof/joinSplit/index.js
  packages/aztec.js/src/proof/proofUtils.js
  packages/aztec.js/src/secp256k1/ecdsa.js
  packages/aztec.js/src/secp256k1/index.js
  packages/aztec.js/src/sign/index.js
  packages/aztec.js/test/abiEncoder/encoderFactory.spec.js
  packages/aztec.js/test/secp256k1/secp256k1.spec.js
  packages/aztec.js/test/sign/sign.spec.js
  packages/contract-addresses/package-lock.json
  packages/contract-artifacts/package-lock.json
  packages/dev-utils/package-lock.json
  packages/dev-utils/package.json
  packages/dev-utils/src/constants.js
  packages/dev-utils/src/index.js
  packages/dev-utils/src/proofs.js
  packages/protocol/contracts/ACE/ACE.sol
  packages/protocol/contracts/ACE/NoteRegistry.sol
  packages/protocol/contracts/ACE/validators/bilateralSwap/BilateralSwapABIEncoder.sol
  packages/protocol/contracts/ACE/validators/dividendComputation/DividendComputationABIEncoder.sol
  packages/protocol/contracts/ACE/validators/joinSplit/JoinSplit.sol
  packages/protocol/contracts/ACE/validators/joinSplit/JoinSplitABIEncoder.sol
  packages/protocol/contracts/ZKERC20/ZKERC20.sol
  packages/protocol/contracts/ZkAsset/IZkAsset.sol
  packages/protocol/contracts/ZkAsset/ZkAsset.sol
  packages/protocol/contracts/ZkAsset/ZkAssetDetailed.sol
  packages/protocol/contracts/ZkAsset/ZkAssetOwnable.sol
  packages/protocol/contracts/ZkAsset/ZkAssetOwnableTest.sol
  packages/protocol/contracts/interfaces/IAZTEC.sol
  packages/protocol/contracts/libs/IntegerUtils.sol
  packages/protocol/contracts/libs/LibEIP712.sol
  packages/protocol/contracts/libs/NoteUtils.sol
  packages/protocol/contracts/libs/ProofUtils.sol
  packages/protocol/contracts/libs/SafeMaths.sol
  packages/protocol/migrations/3_deploy_joinsplit.js
  packages/protocol/migrations/4_deploy_zk_asset.js
  packages/protocol/package-lock.json
  packages/protocol/package.json
  packages/protocol/test/ACE/ACE.js
  packages/protocol/test/ACE/NoteRegistry.js
  packages/protocol/test/ACE/validators/joinSplit/abiEncoder.js
  packages/protocol/test/ACE/validators/joinSplit/index.js
  packages/protocol/test/ZkAsset/ZkAsset.js
  packages/protocol/test/ZkAsset/ZkAssetOwnable.js
Labels: bug, enhancement, feature

#75 Fix PR issues
  packages/protocol/contracts/ACE/ACE.sol
  packages/protocol/contracts/ACE/validators/bilateralSwap/BilateralSwapABIEncoder.sol
Labels: enhancement

#77 Fix constants and allow empty signatures
  packages/aztec.js/package-lock.json
  packages/aztec.js/package.json
  packages/aztec.js/src/proof/bilateralSwap/index.js
  packages/aztec.js/src/proof/bilateralSwap/verifier.js
  packages/aztec.js/src/proof/dividendComputation/index.js
  packages/aztec.js/src/proof/dividendComputation/verifier.js
  packages/aztec.js/src/proof/joinSplit/index.js
  packages/aztec.js/src/proof/joinSplit/verifier.js
  packages/aztec.js/src/proof/proofUtils.js
  packages/aztec.js/src/sign/index.js
  packages/aztec.js/test/abiEncoder/encoderFactory.spec.js
  packages/aztec.js/test/proof/bilateralSwap/verifier.spec.js
  packages/aztec.js/test/proof/dividendComputation/verifier.spec.js
  packages/aztec.js/test/proof/joinSplit/proof.spec.js
  packages/aztec.js/test/proof/joinSplit/verifier.spec.js
  packages/aztec.js/test/sign/sign.spec.js
  packages/dev-utils/package-lock.json
  packages/dev-utils/package.json
  packages/dev-utils/src/constants.js
  packages/protocol/contracts/ACE/ACE.sol
  packages/protocol/contracts/ACE/validators/bilateralSwap/BilateralSwapABIEncoder.sol
  packages/protocol/contracts/ACE/validators/joinSplit/JoinSplitABIEncoder.sol
  packages/protocol/contracts/ZkAsset/ZkAsset.sol
  packages/protocol/migrations/4_deploy_zk_asset.js
  packages/protocol/package-lock.json
  packages/protocol/package.json
  packages/protocol/test/ACE/ACE.js
  packages/protocol/test/ACE/validators/joinSplit/abiEncoder.js
  packages/protocol/test/ACE/validators/joinSplit/index.js
  packages/protocol/test/ZkAsset/ZkAsset.js
  packages/protocol/test/ZkAsset/ZkAssetOwnable.js
Labels: enhancement, feature

#78 Hotfixes
  README.md
  packages/aztec.js/package-lock.json
  packages/aztec.js/package.json
  packages/dev-utils/package-lock.json
  packages/dev-utils/package.json
  packages/dev-utils/src/proofs.js
  packages/protocol/.solcover.js
  packages/protocol/contracts/ACE/validators/bilateralSwap/BilateralSwapABIEncoder.sol
  packages/protocol/contracts/ACE/validators/joinSplit/JoinSplitABIEncoder.sol
  packages/protocol/contracts/ZkAsset/ZkAsset.sol
  packages/protocol/contracts/interfaces/IAZTEC.sol
  packages/protocol/contracts/interfaces/IZkAsset.sol
  packages/protocol/contracts/libs/ProofUtils.sol
  packages/protocol/migrations/3_deploy_joinsplit.js
  packages/protocol/package-lock.json
  packages/protocol/package.json
  packages/protocol/scripts/trace.sh
  packages/protocol/test/ZkAsset/ZkAssetOwnable.js
Labels: bug, enhancement
